# Generated by Django 3.0.7 on 2021-02-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('sex', models.CharField(max_length=32, null=True)),
                ('age', models.CharField(max_length=32, null=True)),
                ('crateTime', models.DateTimeField(null=True)),
                ('salary', models.CharField(max_length=32, null=True)),
                ('shopId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('sum', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=32, null=True)),
                ('per', models.CharField(max_length=32, null=True)),
                ('shopId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('area', models.CharField(max_length=32, null=True)),
                ('boss', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
